package com.srilakshmikanthanp.clipbirdroid.syncing.wan.hub

enum class HubMessageType {
  CLIPBOARD_DISPATCH,
  CLIPBOARD_FORWARD,
  DEVICE_ADDED,
  DEVICE_REMOVED,
  DEVICE_UPDATED,
  NONCE_CHALLENGE_COMPLETED,
  NONCE_CHALLENGE_REQUEST,
  NONCE_CHALLENGE_RESPONSE,
  HUB_DEVICES,
}
